name: Update v2.imba.io
on: [push]
jobs:

  deploy:
    name: Deploy v2
    if: github.ref == 'refs/heads/v2'
    runs-on: ubuntu-latest
    steps:
    - name: Connect to imba.io and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          git -C /home/imba/v2.imba.io stash
          git -C /home/imba/v2.imba.io pull origin v2
          cd /home/imba/v2.imba.io  && \
          /usr/bin/yarn install && \
          /usr/bin/yarn build && \
          RUN_ONCE=true /usr/bin/yarn watch-content
