name: Update imba.io
on: [push]
jobs:

  deploy:
    name: Deploy to imba.io
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Connect to the host and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git -C /home/imba/imba.io stash
          git -C /home/imba/imba.io pull origin master
          /usr/bin/yarn --cwd /home/imba/imba.io install
          sudo systemctl restart imba.io
